exports.GET_IPV4_ADDRESS = 'GET_IPV4_ADDRESS';

exports.STORE_GET_SERVER_PORT = 'STORE_GET_SERVER_PORT';
exports.STORE_GET_ACCEPT_BEHAVIOR = 'STORE_GET_ACCEPT_BEHAVIOR';
exports.STORE_SET_SERVER_PORT = 'STORE_SET_SERVER_PORT';
exports.STORE_SET_ACCEPT_BEHAVIOR = 'STORE_SET_ACCEPT_BEHAVIOR';
